version: '3.0'

services:
  openapi_mock:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    environment:
      #OPENAPI_MOCK_SPECIFICATION_URL: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml'
      OPENAPI_MOCK_SPECIFICATION_URL: 'spec/kesmallads-1.0.1.yaml'
    ports:
      - "8080:8080"
